import { ResourceBuilder } from "@/content/resourceBuilder";

const introToAgentsGoogle = new ResourceBuilder('Intro to Agentic AI by Google')
.setHref('https://cloud.google.com/discover/what-is-agentic-ai')
.setDateOfInclusion(new Date(2026, 3, 15))
.setOverview('The Google definition of what agentic AI is.')
.setTag('agent')
.setTag('chill')
.setFlashcard('Perception', 'The stage where an AI gathers information from its surroundings and various sources, such as sensors or databases, to understand the current situation.')
.setFlashcard('Reasoning', 'The process of using a large language model (LLM) to analyze data, understand context, and formulate potential solutions to a task.')
.setFlashcard('AI agents', 'The autonomous building blocks of agentic AI, designed to perform specific tasks, which are then coordinated to achieve broader objectives.')
.build()

export default introToAgentsGoogle

const transcript = `
Key concepts of agentic AI

Agentic AI systems are designed to operate with a higher degree of autonomy. It works by using AI agents, which are essentially autonomous entities designed to perform specific tasks. At its core, this technology is built on several key components:

    Perception: Agentic AI starts by gathering information from its surroundings and different sources, such as sensors, databases, and user interfaces. This could involve analyzing text, images, or other forms of data to understand the situation.
    Reasoning: Using a large language model (LLM), agentic AI analyzes the gathered data to understand the context, identify relevant information, and formulate potential solutions. For example, if the goal is to schedule a meeting, the LLM can parse the text of emails to identify attendees, available times, and the meeting's purpose.
    Planning: The AI then uses the information it gathered to develop a plan. This involves setting goals, breaking them down into smaller steps, and figuring out the best way to achieve them.
    Action: Based on its plan, the AI takes action. This could involve performing tasks, making decisions, or interacting with other systems.
    Reflection: After taking action, the AI learns from the results. It evaluates whether its actions were successful and uses this feedback to adjust its plans and actions in the future. This continuous cycle of perception, planning, action, and reflection allows agentic AI to learn and improve over time.

Google Cloud’s Vertex AI provides a comprehensive suite of tools for training, building, and deploying AI models, including pre-trained APIs for common tasks and custom training options for advanced use cases. Vertex AI also offers MLOps tools to manage the entire machine learning life cycle, from data preparation to model monitoring, which is crucial for the ongoing development and improvement of agentic AI systems.
Agentic AI versus generative AI

While both agentic AI and generative AI are forms of artificial intelligence and can be used together, they have distinct functionalities. 

Generative AI, as its name suggests, is focused on the creation of new content, such as text, images, code, or music, based on input prompts. The LLM is at the heart of generative AI, and the value is generated by what the model can do and simple extensions of the LLM's capabilities. For example, you can generate or edit content, and even perform simple function calling and chain together various options. 

Agentic AI is a subset of generative AI that is centered around the orchestration and execution of agents that use LLMs as a "brain" to perform actions through tools. Agentic AI goes beyond content creation and function calling by executing actions in underlying systems to achieve higher-level goals. 

For example, generative AI could be used to create marketing materials, while agentic AI could then be used to deploy these materials, track their performance, and automatically adjust the marketing strategy based on the results. In this way, agentic AI can use generative AI as a tool to achieve its goals.
Agentic AI versus AI agents

While the terms "agentic AI" and "AI agents" are often used together, there is a subtle difference. AI agents are the building blocks of agentic AI. Think of AI agents as individual tools in a toolbox, while agentic AI is the coordinated use of those tools to build an entire house. 

While an AI agent might focus on a specific task, agentic AI employs multiple agents to handle complex workflows. Agentic AI acts as an overarching system that coordinates and manages these agents to achieve broader objectives.
Examples of agentic AI automation

Agentic AI is being applied across various industries to automate tasks and optimize processes. Here are a few examples:

Customer service

Agentic AI can empower human agents to tackle more complex problems by managing customer inquiries, resolving issues, and delivering personalized support.

Supply chain management

By analyzing data from diverse sources like sales, inventory, and shipping, agentic AI can optimize supply chains, predict demand, and automate logistics.

Healthcare

Doctors and researchers can use agentic AI to help with diagnosis, treatment planning, and drug discovery by analyzing medical records, research papers, and clinical trials.

Financial services

Agentic AI can help automate fraud detection, risk assessment, and investment strategies by analyzing market data, customer behavior, and financial statements.

Software development

By automating code generation, debugging, and testing, agentic AI can help accelerate the development cycle and improve code quality.
Agentic AI considerations and best practices

Implementing agentic AI in a business requires careful consideration. Here are some key factors to keep in mind:

    Clear objectives: Identify the specific problems that AI agents will solve and how they align with business goals.  
    Data quality and preparation: Agentic AI systems rely on high-quality data to make accurate decisions. Businesses need to ensure their data is accurate, complete, up-to-date, and is properly formatted and integrated for AI consumption. 
    Ethical implications: It's important to consider the ethical implications of using agentic AI and using them responsibly as it can make decisions that have a significant impact on people's lives. This can include addressing potential biases in the data or algorithms that could lead to unfair or discriminatory outcomes. For example, an AI system used for loan approvals should not be biased against certain demographic groups. Additionally, businesses need to be transparent about how agentic AI is being used and ensure that human oversight is in place to prevent unintended consequences.
    Security: Agentic AI systems may be vulnerable to cyberattacks. Businesses need to implement robust security measures to protect these systems and the data they use. This includes protecting against data breaches, unauthorized access, and malicious attacks that could compromise the integrity or confidentiality of the AI system.
    Explainability: Understanding how an agentic AI system makes decisions is important, especially when something goes wrong. Businesses should invest in systems that can provide insights into the decision-making process. Techniques like SHAP (SHapley Additive exPlanations) or LIME (Local Interpretable Model-agnostic Explanations) can help make AI decisions more transparent and understandable. This not only helps build trust but also allows for better debugging and improvement of the AI system.
    Integration: Agentic AI systems need to be integrated with existing business systems, which can be a complex process, requiring careful planning and coordination. This includes ensuring compatibility with existing IT infrastructure, data formats, and business processes. It can also involve addressing potential challenges related to data migration, system integration, and user adoption.
    Monitoring and evaluation: Continuously monitor AI agent performance, address issues, and refine algorithms as needed.  

Businesses should carefully evaluate their needs and resources before implementing agentic AI. They should also be prepared to invest in the necessary infrastructure, expertise, and training to ensure the successful adoption of this technology.
`
