import { ResourceBuilder } from "@/content/resourceBuilder"

const introToAIForCoders = new ResourceBuilder("Enterprise AI Tutorial – Embeddings, RAG, and Multimodal Agents Using Amazon Nova and Bedrock by Auman Debnath")
.setHref("https://youtu.be/HaUe2AN210g?si=SXu6H8Bv5EhhcL8Z")
    .setOverview("A light introduction to the software required for LLMs and mutli-modal LLMs to function.")
    .setDateOfInclusion(new Date(2026, 3, 9))
    .setTag("coding")
    .setFlashcard("CLIP", "Contrastive Language-Image Pre-training, a model architecture for multimodal models.")
    .setFlashcard("BLIP", "Bootstrap Language-Image Pre-training, a model architecture for multimodal models.")
    .setFlashcard("RAG", "Retrieval Augmented Generation, a technique to extract information from data containing text, images, and tables.")
    .setFlashcard("Fine-tuning", "A technique to customize foundational models by training a pre-trained model on labeled proprietary data.")
    .setFlashcard("Continuous pre-training", "A technique for customizing foundational models that uses unlabeled data, requiring organizational expertise and structured data.")
    .setFlashcard("Vector database", "A storage system for proprietary data converted into embeddings, enabling efficient semantic search for relevant information.")
    .setFlashcard("Semantic search", "The process of throwing a question to a vector database to retrieve relevant data chunks based on meaning rather than just keyword matching.")
    .setFlashcard("LangChain", "An orchestration framework that coordinates workflows between vector databases, prompts, and large language models.")
    .setFlashcard("Recursive Character Text Splitter", "A LangChain tool that divides text into smaller chunks of a specified size and overlap to improve retrieval accuracy.")
    .setFlashcard("Positive pairs", "Data set examples where an image is paired with its accurate respective label or caption.")
    .setFlashcard("Negative pairs", "Data set examples where an image is paired with an unrelated label, used to train models to distinguish dissimilar data.")
    .setFlashcard("Text encoder", "A model component that processes text input to generate corresponding numerical embeddings.")
    .setFlashcard("Vision encoder", "A model component that processes image input to generate corresponding numerical embeddings.")
    .setFlashcard("Bedrock Knowledge Bases", "A fully managed service within Amazon Bedrock that automates the end-to-end RAG workflow, including data ingestion and retrieval.")
    .setFlashcard("Data injection pipeline", "The automated workflow of processing raw data, creating embeddings, and storing them in a vector database for retrieval.")
    .setFlashcard("Retrieval API", "An API provided by Bedrock Knowledge Bases that returns relevant data chunks based on a search query.")
    .setFlashcard("Retrieve and Generate API", "An API that retrieves relevant chunks and uses a foundation model to generate a final response in one step.")
    .setFlashcard("Hierarchical chunking", "A strategy that performs semantic search on small child chunks but returns broader parent chunks to provide more context to the LLM.")
    .setFlashcard("Semantic chunking", "A technique that uses an embedding model to divide text into chunks based on meaningful breaks and semantic similarity.")
    .setFlashcard("Function calling", "A capability that allows an LLM to identify and recommend specific external tools or APIs to answer a query without executing them directly.")
    .setFlashcard("Agents", "Advanced AI systems that can reason through complex tasks, decompose them into sub-steps, and autonomously execute tools to achieve a goal.")
    .setFlashcard("Action Groups", "The specific business logic or APIs (often Lambda functions) that an agent can trigger to perform tasks and interact with external systems.")
    .setFlashcard("Byte-Pair Encoding (BPE)", "A subword tokenization method that iteratively merges the most frequent pairs of characters or tokens to create a vocabulary.")
    .setFlashcard("Subword tokenizer", "A tokenization approach that breaks words into smaller meaningful units, balancing vocabulary size and sequence length.")
    .setFlashcard("Word boundary character (/w)", "A special character added during BPE pre-processing to identify the end of a word and preserve boundary information.")
    .setFlashcard("Merge operation", "The iterative step in BPE where the most frequently occurring pair of tokens is combined into a single new token.")
    .setFlashcard("Self-supervised learning", "A training approach where a model learns from unlabeled data by generating its own targets, such as predicting the next token in a sequence.")
    .setFlashcard("Sliding window technique", "A data sampling method used to create multiple training examples from a single text by shifting the input-target window by one token at a time.")
    .setFlashcard("Context size", "The fixed number of previous tokens that an LLM considers as input when predicting the next token in a sequence.")
    .setFlashcard("Token embeddings", "Numerical vector representations of individual tokens, where each token ID is mapped to a high-dimensional space.")
    .setFlashcard("Absolute positional embeddings", "Numerical vectors added to token embeddings to provide the model with information about the specific position of a token within a sequence.")
    .setFlashcard("Embeddings", "Numerical vector representations of data that allow models to process text, audio, and video in a mathematical space.")
    .setFlashcard("Tokenization", "The fundamental step of breaking raw text into smaller segments called tokens (words or subwords) before numerical conversion.")
    .setFlashcard("Token ID", "A unique integer identifier assigned to each token in a vocabulary to facilitate model processing.")
    .setFlashcard("Out of vocabulary (OOV)", "A situation where a model encounters a word during inference that was not part of its initial training vocabulary.")
    .setFlashcard("Special tokens", "Specific markers like [UNK] or [EOS] used by tokenizers to manage unknown words and sequence boundaries.")
    .setFlashcard("Multimodal models", "Advanced AI systems capable of processing and integrating different types of data such as text, image, video, and audio.")
    .setFlashcard("Vision Transformer (ViT)", "An architecture that leverages transformer models to process images by dividing them into numerical patches.")
    .setFlashcard("Patched image", "An image tokenization strategy where an image is divided into small, fixed-size blocks and flattened into vectors for transformer processing.")
    .setFlashcard("Amazon Bedrock", "A fully managed AWS service that provides access to high-performing foundation models from multiple providers via a single API.")
    .setFlashcard("Bedrock Client", "The control plane API for Bedrock used to list available models, manage provisioned throughput, and check model capabilities.")
    .setFlashcard("Bedrock Runtime Client", "The data plane API for Bedrock used to interact with models for tasks like generating text or embeddings.")
    .setFlashcard("Vector normalization", "The mathematical process of scaling an embedding vector so its magnitude equals one, ensuring uniformity across different data points.")
    .setFlashcard("Cosine similarity", "A similarity metric calculated as the dot product of two vectors divided by the product of their magnitudes, used to evaluate semantic relatedness.")
    .build()

export default introToAIForCoders
